Repository woowa-techcamp-2022/web-moneybook-08, pull requests merged in 2022-07, with the labels that each got.

#8 feat: 이슈 템플릿 및 PR 템플릿 수정
  .github/ISSUE_TEMPLATE.md
  .github/PULL_REQUEST_TEMPLATE.md
Labels: feature

#11 feat: 렌더링 시스템 구현
  .gitignore
  frontend/app.js
  frontend/components/Component.js
  frontend/components/Header.js
  frontend/index.js
  frontend/pages/MainPage.js
  frontend/webpack.config.js
  package-lock.json
  package.json
Labels: feature

#12 feat:페이지 라우팅 구현
  backend/app.js
  dist/index.html
  dist/main.js
  frontend/app.js
  frontend/dist/index.html
  frontend/dist/main.js
  frontend/pages/CalendarPage.js
  frontend/pages/StatisticsPage.js
  frontend/pages/index.js
  frontend/public/index.html
  frontend/webpack.config.js
  package-lock.json
  package.json
Labels: feature

#15 feat: app.js 리팩터링
  frontend/app.js
  frontend/components/Header.js
  frontend/index.js
  frontend/public/index.html
  frontend/utils.js
Labels: feature, refactor

#19 fix: 라우터 및 페이지 렌더링 수정
  .github/PULL_REQUEST_TEMPLATE.md
  dist/index.html
  dist/main.js
  frontend/app.js
  frontend/components/Header.js
  frontend/index.js
Labels: bug, feature, refactor

#21 bug: express 기본 라우팅 index.html 향하도록 수정
  backend/app.js
  dist/main.js
  package.json
Labels: bug

#22 Feat: global css 셋업
  frontend/assets/icons/calendar.svg
  frontend/assets/icons/chart.svg
  frontend/assets/icons/check.svg
  frontend/assets/icons/text.svg
  frontend/style/style.scss
Labels: feature, style

#23 style: header 마크업 및 스타일
  frontend/assets/icons/left-arrow.svg
  frontend/assets/icons/right-arrow.svg
  frontend/components/Header.js
  frontend/components/header.scss
  frontend/public/index.html
  frontend/style/color.scss
  frontend/style/normalize.scss
  frontend/style/style.scss
  frontend/webpack.config.js
Labels: style

#25 feat: item list 컴포넌트 마크업
  frontend/components/listItem/ListItem.scss
  frontend/components/listItem/listItem.js
  frontend/pages/MainPage.js
  frontend/store/historyStore.js
  frontend/style/style.scss
Labels: feature

#27 feature: modal popup 컴포넌트 추가
  frontend/app.js
  frontend/components/Header/Header.js
  frontend/components/Header/header.scss
  frontend/components/Modal/Modal.js
  frontend/components/Modal/modal.scss
Labels: feature

#28 Feat: category constant 객체 구현 및 listItem 에 적용
  frontend/app.js
  frontend/components/Component.js
  frontend/components/Header/Header.js
  frontend/components/listItem/ListItem.scss
  frontend/components/listItem/listItem.js
  frontend/pages/MainPage.js
  frontend/store/historyStore.js
  frontend/style/color.scss
  frontend/style/style.scss
  frontend/utils.js
  frontend/utils/constant.js
Labels: feature, style

#34 feat: 메인페이지(내역페이지) Input bar 구현
  frontend/app.js
  frontend/assets/icons/check-submit.svg
  frontend/assets/icons/delete-icon.svg
  frontend/assets/icons/down-arrow.svg
  frontend/assets/icons/minus-icon.svg
  frontend/components/Header/Header.js
  frontend/components/InputBar/InputBar.js
  frontend/components/InputBar/inputbar.scss
  frontend/components/listItem/listItem.js
  frontend/pages/MainPage.js
  frontend/store/historyStore.js
  frontend/style/style.scss
Labels: feature, style

#33 feat: 캘린더 컴포넌트 구현 및 캘린더 페이지 레이아웃 작업
  frontend/components/Calendar/Calendar.js
  frontend/components/Calendar/calendar.scss
  frontend/components/Header/header.scss
  frontend/components/InputBar/inputbar.scss
  frontend/components/listItem/listItem.js
  frontend/pages/CalendarPage.js
  frontend/pages/MainPage.js
  frontend/store/historyStore.js
  frontend/style/color.scss
  frontend/style/style.scss
  package-lock.json
Labels: feature, style

#37 fix: 오타 수정
  frontend/components/Calendar/Calendar.js
  frontend/pages/CalendarPage.js
Labels: bug

#38 feat: store 구현 완료
  frontend/app.js
  frontend/pages/StatisticsPage.js
  frontend/store/statisticsStore.js
  frontend/store/store.js
Labels: feature, pair

#41 feat: db셋업 및 샘플 api 구현
  .gitignore
  backend/api/histories/historiesController.js
  backend/api/histories/historiesRouter.js
  backend/api/histories/historiesService.js
  backend/app.js
  backend/db.js
  backend/middleware/dbConnection.js
  package-lock.json
  package.json
Labels: feature, server, pair

#44 Feat: date formmater 유틸 함수 구현 및 테스트 코드 작성
  backend/__test__/date.test.js
  backend/api/histories/historiesService.js
  backend/utils/date.js
  package-lock.json
  package.json
Labels: feature, server

#46 feat: 머니북 내역 추가, 수정, 삭제 API 구현
  backend/api/categories/categoriesService.js
  backend/api/histories/historiesController.js
  backend/api/histories/historiesRouter.js
  backend/api/histories/historiesService.js
Labels: feature, server

#48 Feat: 내역페이지 리스트아이템 추가 기능 구현 및 체크박스 콘텐츠 구현
  frontend/assets/icons/checkbox-small-active.svg
  frontend/components/CheckboxContents/CheckboxContents.js
  frontend/components/CheckboxContents/checkboxContents.scss
  frontend/components/listItem/ListItem.scss
  frontend/components/listItem/listItem.js
  frontend/pages/MainPage.js
  frontend/store/historyStore.js
  frontend/utils/constant.js
Labels: feature, style

#51 feat: 클라이언트 API 기본 셋팅
  frontend/api/category.js
  frontend/api/history.js
  frontend/api/index.js
  frontend/api/paymentType.js
Labels: feature, pair

#56 feat: 내역 조회 api 가공 함수 구현 및 내역, 캘린더 페이지 적용
  backend/api/histories/historiesController.js
  frontend/api/history.js
  frontend/api/index.js
  frontend/app.js
  frontend/components/Calendar/Calendar.js
  frontend/components/Calendar/calendar.scss
  frontend/components/InputBar/InputBar.js
  frontend/components/listItem/listItem.js
  frontend/pages/MainPage.js
  frontend/store/historyStore.js
Labels: feature, pair

#58 feat: Input bar 결제수단 추가 및 삭제 API 연동
  backend/api/categories/categoriesController.js
  backend/api/histories/historiesController.js
  backend/api/paymentTypes/paymentTypesController.js
  backend/api/paymentTypes/paymentTypesRouter.js
  backend/api/paymentTypes/paymentTypesService.js
  backend/app.js
  frontend/api/paymentType.js
  frontend/components/InputBar/InputBar.js
  frontend/components/InputBar/inputbar.scss
  frontend/components/Modal/Modal.js
  frontend/components/Modal/modal.scss
Labels: feature, style

#59 feat: 내역 추가 api 연동
  backend/api/histories/historiesController.js
  backend/api/histories/historiesService.js
  backend/api/paymentTypes/paymentTypesController.js
  frontend/api/history.js
  frontend/components/InputBar/InputBar.js
  frontend/components/InputBar/inputbar.scss
  frontend/components/listItem/listItem.js
  frontend/pages/MainPage.js
  frontend/store/historyStore.js
  frontend/store/store.js
  frontend/style/style.scss
Labels: feature, server

#61 feat: 내역수정 api 연동 및 체크박스 컨텐츠 체크에 따라 렌더링 변경되도록 구현
  backend/api/histories/historiesController.js
  backend/api/histories/historiesService.js
  frontend/api/history.js
  frontend/components/CheckboxContents/CheckboxContents.js
  frontend/components/CheckboxContents/checkboxContents.scss
  frontend/components/InputBar/InputBar.js
  frontend/components/InputBar/inputbar.scss
  frontend/components/listItem/listItem.js
  frontend/pages/MainPage.js
  frontend/store/historyStore.js
Labels: feature, server

#63 feat: 달력 화살표 클릭 시 날짜 바뀌고 데이터 새로 가져오도록 구현 및 path에 따라 아이콘 활성화 구현
  frontend/app.js
  frontend/components/Header/Header.js
  frontend/components/Header/header.scss
  frontend/store/historyStore.js
  frontend/utils/date.js
Labels: feature, style

#64 feat: 도넛 차트 구현
  frontend/.DS_Store
  frontend/api/history.js
  frontend/app.js
  frontend/components/Calendar/calendar.scss
  frontend/components/DoughnutChart/DoughnutChart.js
  frontend/components/DoughnutChart/doughnutChart.scss
  frontend/components/StatisticContents/StatisticContents.js
  frontend/components/StatisticContents/statisticContents.scss
  frontend/components/listItem/listItem.js
  frontend/pages/StatisticsPage.js
  frontend/pages/samplePage.js
  frontend/store/statisticsStore.js
  frontend/style/color.scss
  frontend/style/style.scss
Labels: feature, style

#68 fix: 잔잔바리 버그들 수정
  frontend/components/Calendar/Calendar.js
  frontend/components/Calendar/calendar.scss
  frontend/components/CheckboxContents/CheckboxContents.js
  frontend/components/listItem/listItem.js
  frontend/store/historyStore.js
Labels: bug

#69 fix: getHistory API 쿼리문 수정
  backend/api/histories/historiesService.js
Labels: bug, server

#70 fix: input bar 내 select - ux개선
  frontend/components/InputBar/InputBar.js
Labels: bug, server

#73 feat: 카테고리별 최근 6개월 지출 데이터 API 완료
  backend/api/categories/categoriesController.js
  backend/api/categories/categoriesService.js
  backend/utils/date.js
Labels: feature, server

#76 fix: 파일명, import 시 path명 변경
  frontend/components/listItem/listItem.js
  frontend/pages/MainPage.js
Labels: bug

#78 feat: 차트페이지 직선 그래프 구현
  frontend/components/.DS_Store
  frontend/components/InputBar/InputBar.js
  frontend/components/LineChart/LineChart.js
  frontend/components/LineChart/lineChart.scss
  frontend/components/StatisticContents/StatisticContents.js
  frontend/components/StatisticContents/statisticContents.scss
Labels: feature

#81 feat: 리드미 작성
  README.md
Labels: feature

#82 feat: 차트 페이지 db 데이터 연결
  frontend/api/category.js
  frontend/app.js
  frontend/components/DoughnutChart/DoughnutChart.js
  frontend/components/DoughnutChart/doughnutChart.scss
  frontend/components/StatisticContents/StatisticContents.js
  frontend/pages/StatisticsPage.js
  frontend/store/statisticsStore.js
  frontend/store/store.js
Labels: feature

#85 feat: 라인 차트 데이터 해당 월부터 그려지도록 구현
  frontend/components/DoughnutChart/DoughnutChart.js
  frontend/components/LineChart/LineChart.js
  frontend/components/StatisticContents/StatisticContents.js
  frontend/components/StatisticContents/statisticContents.scss
  frontend/pages/StatisticsPage.js
Labels: feature

#86 feat: 선택된 카테고리에 따라서 리스트되도록 수정
  backend/api/categories/categoriesController.js
  frontend/components/StatisticContents/StatisticContents.js
  frontend/store/statisticsStore.js
Labels: feature
